# Generated by Django 4.2.16 on 2026-02-10 05:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('profile_picture', models.UUIDField(blank=True, null=True)),
                ('banner_picture', models.UUIDField(blank=True, null=True)),
                ('biography', ckeditor.fields.RichTextField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('threads', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('youtube', models.URLField(blank=True, default='')),
                ('tiktok', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('gitlab', models.URLField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
