# Generated by Django 4.2.16 on 2026-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo'),
        ),
    ]
