# Generated by Django 4.2.16 on 2026-02-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_device_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
