# Generated by Django 4.2.16 on 2026-02-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_useraccount_code'),
    ]

    operations = [
    ]
