# Generated by Django 4.2.16 on 2026-02-05 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_generate_user_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='userdevice',
            options={'verbose_name': 'Dispositivo de usuario', 'verbose_name_plural': 'Dispositivos de usuario'},
        ),
        migrations.AddField(
            model_name='userdevice',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_authorized', to=settings.AUTH_USER_MODEL),
        ),
    ]
