# Generated by Django 4.2.16 on 2026-02-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_device_options_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_sistema', models.CharField(db_index=True, max_length=255)),
                ('numero_serie_cpu', models.CharField(db_index=True, max_length=255)),
                ('numero_serie_disco', models.CharField(db_index=True, max_length=255)),
                ('baseboard_serial', models.CharField(db_index=True, max_length=255)),
                ('bios_serial', models.CharField(db_index=True, max_length=255)),
                ('mac_address', models.CharField(db_index=True, max_length=255)),
                ('nombre_maquina', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='authentication.device')),
            ],
        ),
    ]
