# Generated by Django 4.2.16 on 2026-02-09 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_devicefingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('url', models.URLField()),
                ('icono', models.CharField(default='📦', max_length=50)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolUniversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('nivel', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sistemas', models.ManyToManyField(blank=True, related_name='roles', to='authentication.sistema')),
            ],
            options={
                'verbose_name': 'Rol Universal',
                'verbose_name_plural': 'Roles Universales',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REFRESH', 'Token Refresh'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('SESSION_EXPIRED', 'Session Expired'), ('DEVICE_MISMATCH', 'Device Hash Mismatch')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='authenticat_user_id_c5f5bc_idx'), models.Index(fields=['action', '-timestamp'], name='authenticat_action_2f91bd_idx')],
            },
        ),
    ]
