# Generated by Django 4.2.16 on 2026-02-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0014_sistema_roluniversal_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='roluniversal',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rol_universal', to='auth.group', verbose_name='Grupo de Django Relacionado'),
        ),
    ]
