# Generated by Django 4.2.16 on 2026-02-06 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('url_frontend', models.URLField()),
                ('url_backend', models.URLField()),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAplicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.aplicacion')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permisos')),
            ],
            options={
                'verbose_name': 'Grupo de Aplicación',
                'verbose_name_plural': 'Grupos de Aplicación',
                'unique_together': {('group', 'aplicacion')},
            },
        ),
        migrations.CreateModel(
            name='UserGroupAplicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.groupaplicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario en Grupo de Aplicación',
                'verbose_name_plural': 'Usuarios en Grupos de Aplicación',
                'unique_together': {('user', 'group_aplicacion')},
            },
        ),
    ]
